using Microsoft.AspNetCore.Mvc;
using System.Linq;
using PTrucks.Models;
using PTrucks.Data;


namespace PTrucks.Controllers
{
    public class DeviceLocationController : Controller
    {
        private readonly PTDbContext _db;
        
        public DeviceLocationController(PTDbContext dbContext)
        {
            _db = dbContext;
        }

        //autogenerated
        public IActionResult Index()
        {
            var trucks = _db.GetTrucks();
            return View(trucks);
            
        }
    }
}
